/**
 * Guards the deployment configuration.
 *
 * The production PostgreSQL schema is generated from the canonical SQLite one,
 * and the tests run against SQLite — so nothing else would notice if a model
 * change never reached the schema Neon actually migrates.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const apiRoot = path.resolve(import.meta.dirname, '..');
const read = (relative: string) => readFileSync(path.join(apiRoot, relative), 'utf8');

describe('production schema', () => {
  it('is in sync with the canonical schema', () => {
    // Throws (non-zero exit) if prisma/production/schema.prisma is stale.
    expect(() =>
      execFileSync('node', ['prisma/generate-production-schema.mjs', '--check'], {
        cwd: apiRoot,
        stdio: 'pipe',
      }),
    ).not.toThrow();
  });

  it('targets PostgreSQL over an unpooled connection for migrations', () => {
    const schema = read('prisma/production/schema.prisma');
    expect(schema).toContain('provider = "postgresql"');
    expect(schema).toContain('url      = env("DATABASE_URL")');
    // Prisma migrations cannot run through a connection pooler.
    expect(schema).toContain('directUrl = env("DIRECT_URL")');
  });

  it('has a PostgreSQL migration covering every model', () => {
    const migration = read('prisma/production/migrations/0_init/migration.sql');
    const lock = read('prisma/production/migrations/migration_lock.toml');

    expect(lock).toContain('postgresql');

    for (const model of [
      'User',
      'UserPreference',
      'UserInterest',
      'RefreshToken',
      'PasswordResetToken',
      'Country',
      'City',
      'Category',
      'Place',
      'PlaceCategory',
      'Photo',
      'OpeningHour',
      'SavedPlace',
      'Itinerary',
      'ItineraryStop',
    ]) {
      expect(migration, `missing table ${model}`).toContain(`CREATE TABLE "${model}"`);
    }
  });
});

describe('build configuration', () => {
  it('starts the file the build actually emits', () => {
    const pkg = JSON.parse(read('package.json')) as {
      scripts: Record<string, string>;
    };
    const buildConfig = JSON.parse(read('tsconfig.build.json')) as {
      compilerOptions: { outDir: string; rootDir: string };
    };

    // rootDir "." means sources land under dist/<sourceDir>/…, so the start
    // script must point at dist/src/server.js, not dist/server.js.
    expect(buildConfig.compilerOptions.rootDir).toBe('.');
    expect(pkg.scripts.start).toBe('node dist/src/server.js');
    expect(pkg.scripts.build).toContain('tsconfig.build.json');
  });

  it('keeps tests out of the production build', () => {
    const buildConfig = JSON.parse(read('tsconfig.build.json')) as {
      exclude: string[];
      include: string[];
    };
    expect(buildConfig.exclude).toContain('tests');
    expect(buildConfig.include).not.toContain('tests/**/*.ts');
  });
});

describe('render blueprint', () => {
  const blueprint = read('../render.yaml');

  it('runs migrations before the new version goes live', () => {
    expect(blueprint).toContain('preDeployCommand');
    expect(blueprint).toContain('prisma:prod:deploy');
  });

  it('generates the PostgreSQL client at build time', () => {
    expect(blueprint).toContain('prisma:prod:generate');
  });

  it('never hardcodes a secret, and asks for each one', () => {
    // A secret may either be prompted for (`sync: false`) or generated by
    // Render (`generateValue: true`) — but it must never carry a literal value.
    for (const key of [
      'DATABASE_URL',
      'DIRECT_URL',
      'JWT_ACCESS_SECRET',
      'JWT_REFRESH_SECRET',
      'R2_ACCESS_KEY_ID',
      'R2_SECRET_ACCESS_KEY',
    ]) {
      const declaration = new RegExp(
        `key:\\s*${key}\\s*\\n\\s*(sync:\\s*false|generateValue:\\s*true)`,
      );
      expect(
        blueprint,
        `${key} must use sync: false or generateValue: true, never a literal`,
      ).toMatch(declaration);
    }

    // Guard against a credential being pasted in during a hurry.
    expect(blueprint).not.toMatch(/postgres:\/\/[^\s"]*:[^\s"]*@/);
    expect(blueprint).not.toMatch(/\bsk_[A-Za-z0-9]{16,}/);
  });

  it('points the health check at the endpoint the API serves', () => {
    expect(blueprint).toContain('healthCheckPath: /health');
  });
});
